dockerImage: backstage
dockerFile: Dockerfile
dockerPlatform:
  - linux/amd64
  - linux/arm64
dockerRegistry: ghcr.io
dockerProject: jdmacd

branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - "@codedependant/semantic-release-docker"