---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: central
spec:
  refreshInterval: 300s
  secretStoreRef:
    kind: ClusterSecretStore
    name: cnpg-cluster-secrets
  target:
    name: central
    template:
      engineVersion: v2
      data:
        url: 'postgres://{{ .user }}:{{ .password }}@{{ .host }}:{{ .port }}/{{ .dbname }}'
  dataFrom:
  - extract:
      key: backstage