---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: central
spec:
  refreshInterval: 300s
  secretStoreRef:
    kind: ClusterSecretStore
    name: cnpg-cluster-secrets
  target:
    name: central
    template:
      engineVersion: v2
      data:
        POSTGRES_URL: 'postgres://{{ .user }}:{{ .password }}@{{ .host }}:{{ .port }}/{{ .dbname }}'
        POSTGRES_HOST: '{{ .host }}'
        POSTGRES_PORT: '{{ .port }}'
        POSTGRES_USER: '{{ .user }}'
        POSTGRES_PASSWORD: '{{ .password }}'
  dataFrom:
  - extract:
      key: backstage
---
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage
spec:
  refreshInterval: 300s
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    name: backstage
  dataFrom:
  - extract:
      key: 9644eb16-81bf-4b8e-8661-b3730174afba