---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: backstage
spec:
  serviceName: backstage
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      serviceAccountName: backstage
      containers:
        - name: backstage
          image: ghcr.io/jdmacd/backstage:main
          ports:
            - containerPort: 7007
              name: http
          volumeMounts:
            - name: config
              mountPath: /app/app-config.production.yaml
              subPath: app-config.production.yaml
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: central
                  key: POSTGRES_URL
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: central
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: central
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: central
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: central
                  key: POSTGRES_PASSWORD
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 7007
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 7007
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: backstage
